### ISSUE TITLE
Cannot find module './Main.js'

### ISSUE THREAD

**Issue by gavr123456789** [ryyppy/simple-wallet-prototype#1]
Linux: Arch
Node: v18.7.0

`npm install`  
`npx rescript build -w` in one term
`npm start` in another
Got error:
```
$ electron-forge start
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Compiling Main Process Code
✔ Launch Dev Servers
✔ Compiling Preload Scripts
✔ Launching Application


Webpack Output Available: http://localhost:9000

App threw an error during load
Error: Cannot find module './Main.js'
    at webpackMissingModule (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:65)
    at Object../src/main.js (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:149)
    at __webpack_require__ (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:21:30)
    at /home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:85:18
    at Object.<anonymous> (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './Main.js'
    at webpackMissingModule (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:65)
    at Object../src/main.js (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:149)
    at __webpack_require__ (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:21:30)
    at /home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:85:18
    at Object.<anonymous> (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
[24439:0730/034826.658214:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Done in 6.18s.
```

**Comment by gavr123456789** [comment]
Updated electron to the latest version via `yarn add -D electron` and now I dont have error `[24439:0730/034826.658214:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.` at the end.  
But all other are the same

```
Webpack Output Available: http://localhost:9000

App threw an error during load
Error: Cannot find module './Main.js'
    at webpackMissingModule (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:65)
    at ./src/main.js (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:149)
    at __webpack_require__ (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:21:30)
    at /home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:85:18
    at Object.<anonymous> (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:88:10)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './Main.js'
    at webpackMissingModule (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:65)
    at ./src/main.js (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:1388:149)
    at __webpack_require__ (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:21:30)
    at /home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:85:18
    at Object.<anonymous> (/home/gavr/rescript/simple-wallet-prototype/.webpack/main/index.js:88:10)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
webpack built 584b43810912dc2c9b4f in 4426ms
```

Also now I got empty window

![image](https://user-images.githubusercontent.com/30507409/181864602-f9408cd3-9ea6-4fcd-9acd-f2060e312d26.png)


I don't know much about electron, I just want to use rescript. It seems that some of the dependencies are very outdated, given that electron 10 was used.
